<style type="text/css">
    .grid table td.first, .grid table td.last {
        border-right: 0;
        width: 90px;
        text-align: right;
    }
    .grid tr.even, .grid tr.even tr {
        background: #f6f6f6;
        display: table;
        width: 100%;
    }
</style>
<input id="freegiftsymbol" type="hidden" value="<?php echo $block->showCurrencyLabel()  ?>"/>
<div class="col-m-12">
    <p class="switcher a-right">
        <label for="store_switcher"><?php echo __('Date Range:') ?></label>
        <select name="report_range" id="report_range">
            <option value="1"><?php echo __('Last 24 Hours')?></option>
            <option value="2"><?php echo __('Last Week')?></option>
            <option value="3"><?php echo __('Last Month')?></option>
            <option value="4"><?php echo __('Last 7 days')?></option>
            <option value="5" selected="selected"><?php echo __('Last 30 days')?></option>
            <option value="7"><?php echo __('Custom')?></option>
        </select>
        <span id="custom_range" style="display: none">
            <label for="from_date"><?php echo __('From:') ?></label>
<!--            <input type="text" name="report_from" id="report_from" style="width: 80px;"/>-->
            <input type="text" name="report_from" id="report_from"  style="width: 80px;">
            <label for="to_date"><?php echo __('To:') ?></label>
<!--            <input type="text" name="report_to" id="report_to" style="width: 80px;"/>-->
            <input type="text" name="report_to" id="report_to" style="width: 80px;"/>
            <input type="button" id="report_refresh" value="<?php echo __('Refresh') ?>" style="background: #E9E3E3;border: 1px solid #ccc;padding: 2px;">

        </span>

                        <script type="text/javascript">
                            require([
                                "jquery",
                                "mage/calendar"
                            ], function($){
                                $('#report_from').datepicker({
                                        prevText: '&#x3c;zurück', prevStatus: '',
                                        prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                                        nextText: 'Vor&#x3e;', nextStatus: '',
                                        nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                                        monthNames: ['January','February','March','April','May','June',
                                            'July','August','September','October','November','December'],
                                        monthNamesShort: ['January','February','March','April','May','June',
                                            'July','August','September','October','November','December'],
                                        dayNames: ['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
                                        dayNamesShort: ['Sun','Mon','Tue','Wed','Thu','Fra','Sat'],
                                        dayNamesMin: ['Sun','Mon','Tue','Wed','Thu','Fra','Sat'],
                                        showMonthAfterYear: false,
                                        dateFormat:'m/d/yy '
                                    }
                                );
                                $('#report_to').datepicker({
                                        prevText: '&#x3c;zurück', prevStatus: '',
                                        prevJumpText: '&#x3c;&#x3c;', prevJumpStatus: '',
                                        nextText: 'Vor&#x3e;', nextStatus: '',
                                        nextJumpText: '&#x3e;&#x3e;', nextJumpStatus: '',
                                        monthNames: ['January','February','March','April','May','June',
                                            'July','August','September','October','November','December'],
                                        monthNamesShort: ['January','February','March','April','May','June',
                                            'July','August','September','October','November','December'],
                                        dayNames: ['Sonntag','Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag'],
                                        dayNamesShort: ['So','Mo','Di','Mi','Do','Fr','Sa'],
                                        dayNamesMin: ['So','Mo','Di','Mi','Do','Fr','Sa'],
                                        showMonthAfterYear: false,
                                        dateFormat:'m/d/yy'
                                    }
                                );
                            });
                        </script>

    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="box-left entry-edit" style="width: 350px; float: right">
            <div class="entry-edit-head"><h4><?php echo __('Statistics')?></h4></div>
            <fieldset class="np">
                <div class="grid np">
                    <table cellspacing="0" style="border:0;" id="statisticsGrid_table" class="">
                        <tbody>
                            <tr class="even pointer">
                                <td class=""><?php echo __('Total Order Value')?></td>
                                <td class="a-right a-right last" id="total_order">...</td>
                            </tr>
                            <tr class="even pointer">
                                <td class=""><?php echo __('Total Gift Value')?></td>
                                <td class="a-right a-right last" id="total_gift">...</td>
                            </tr>
                            <tr class="even pointer">
                                <td class=""><?php echo __('Average Gift Value per Customer')?></td>
                                <td class="a-right a-right last" id="avg_gift_customer">...</td>
                            </tr>
                            <tr class="even pointer">
                                <td class=""><?php echo __('Average Gift Value per Order')?></td>
                                <td class="a-right a-right last" id="avg_gift_order">...</td>
                            </tr>
                    </table>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="col-md-8" style="min-height: 350px;">
        <div id="rwp-container" style=" width: 850px; height: 300px; margin-top: 50px; position: absolute; ">
    </div>
</div>

<script type="text/javascript">
require([
    "prototype"
], function(){
    document.observe("dom:loaded", function() {
        window.mwReport = new MW.FreeGift.Report.Dashboard({url: '<?php echo $block->getUrl('mw_freegift/report_dashboard/dashboard')?>'});
    });
});
</script>

