<div id="container-report" style="height: 400px; min-width: 310px"></div>

<script>

    require(['jquery','mw/highstock'], function($) {
        $(document).ready(function($) {
            require(['mw/exporting'], function($) {
            var dataOrder = <?php echo $this->getOrderData() ?>;
            var dataFreeGift = <?php echo $this->getFreeGiftData() ?>;

            // Create the chart
            Highcharts.stockChart('container-report', {


                rangeSelector: {
                    selected: 0
                },

                title: {
                    text: 'Free Gift Report'
                },

                tooltip: {
                    style: {
                        width: '200px'
                    },
                    valueDecimals: 4,
                    shared: true
                },

                yAxis: {
                    title: {
                        text: 'Exchange rate'
                    }
                },

                series: [{
                    name: 'Order Value',
                    data: dataOrder,
                    id: 'dataseries'

                    // the event marker flags
                },
                    {
                        name: 'Free Gift Value',
                        data: dataFreeGift,
                        id: 'dataseries'

                        // the event marker flags
                    },
                    {
                        type: 'flags',
                        onSeries: 'dataseries',
                        shape: 'circlepin',
                        width: 16
                    }]

            });
            });
        })
    });
</script>
