<script type="text/javascript">
    hasGiftProduct = false;
</script>
<?php
$productIds =  $block->getProductIds();
$oriProductId =  $block->getOriProductId();
if(count($productIds) > 0):
?>
<div class="mw-fg-catalog-list">
    <div class="freegift_header">
        <h5>Free Gift</h5>
    </div>
    <div class="freegift_catalog_container clearer">
        <ul class="freegift">
            <?php foreach($productIds as $giftData):
            if($giftData['rule_gift_ids'] != "") :
            $product = $block->getProductGiftData($giftData['rule_gift_ids']);
            if($product->isSaleable()) :
            ?>
            <li class="mw-fg-items">
                <a id="stay-target-<?php echo $giftData['rule_id'].'_'.$oriProductId.'_'.$giftData['rule_gift_ids']; ?>" href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $block->escapeHtml($product->getName()); ?>" class="product-image">
                    <img src="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($product, 'category_page_list')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(38,40)->getUrl(); ?>" alt="" height="38" width="40">
                </a>
                <div style="display: none;" id="stay-content-<?php echo $giftData['rule_id'].'_'.$oriProductId.'_'.$giftData['rule_gift_ids']; ?>" class="mw-fg-item">
                    <div class="mw-fg-item-options">
                        <div class="mw-fg-item-option-title"><?php echo $giftData['name'] ?></div>
                        <div class="mw-fg-item-option-ct">
                            <p class="mw-fg-image-item">
                                <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $block->escapeHtml($product->getName()); ?>">
                                    <img src="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($product, 'category_page_list')->constrainOnly(TRUE)->keepAspectRatio(TRUE)->keepFrame(TRUE)->resize(135,135)->getUrl(); ?>" alt="" height="135" width="135">
                                </a>
                            </p>
                            <p class="mw-fg-item-name">
                                <a href="<?php echo $product->getProductUrl(); ?>" title="<?php echo $block->escapeHtml($product->getName()); ?>"><?php echo $block->escapeHtml($product->getName()); ?></a>
                            </p>
                        </div>
                    </div>
                </div>
            </li>
            <?php endif; ?>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
        <div style="clear: both;"></div>
    </div>
</div>
<?php endif; ?>