<?php

$_dataHelper = $this->helper('MW\FreeGift\Helper\Data');
if (1 == 0) :
    if($block->getSessionManager()->getCity()) {
        $cityval = $block->getSessionManager()->getCity();
    } else {
        $cityval = $block->getRegistry()->registry('City');
    }

    if($block->getSessionManager()->getRegionId()) {
        $regionidval = $block->getSessionManager()->getRegionId();
    } else {
        $regionidval = $block->getRegistry()->registry("Regionid");
    }

    if($block->getSessionManager()->getRegion()) {
        $regionval = $block->getSessionManager()->getRegion();
    } else {
        $regionval = $block->getRegistry()->registry('Regionname');
    }

    if($block->getSessionManager()->getPostcode()) {
        $postcodeval = $block->getSessionManager()->getPostcode();
    } else {
        $postcodeval = $block->getRegistry()->registry('Zipcode');
    }
    ?>

    <script type="text/javascript">
        require([
            'jquery'
        ], function($) {
            isLogged = <?php echo ($block->getCustomerSession()->isLoggedIn() ? 1 : 0) ?>;
            var ip = "<?php echo getenv('REMOTE_ADDR') ?>";

            // Geoip for form
            window.geoip = {};
            window.geoip.postcode = '<?php echo $postcodeval?>';
            window.geoip.city = '<?php echo $cityval?>';
            window.geoip.region = '<?php echo $regionval?>';
            window.geoip.regionid = '<?php echo $regionidval?>';
        });
    </script>

<?php endif; ?>

<?php //if (1 == 0) :
//    $design = $_dataHelper->getStoreConfig('onestepcheckout/display_setting/style');
//    $roundCorner = $_dataHelper->getStoreConfig('onestepcheckout/display_setting/round_corner');
//    ?>
<!--    --><?php //if ($design == 2 || $design == 3) : ?>
<!--    <link rel="stylesheet" type="text/css" href="--><?php //echo $block->getViewFileUrl('MW_Onestepcheckout::css/onestepcheckout_flat.css') ?><!--" />-->
<!---->
<!--    --><?php //if($design == 3) : ?>
<!--        <link rel="stylesheet" type="text/css" href="--><?php //echo $block->getViewFileUrl('MW_Onestepcheckout::css/onestepcheckout_classic.css') ?><!--" />-->
<!--    --><?php //endif; ?>
<!---->
<!--    --><?php //if ($roundCorner == 1) : ?>
<!--        <link rel="stylesheet" type="text/css" href="--><?php //echo $block->getViewFileUrl('MW_Onestepcheckout::css/onestepcheckout_corner.css') ?><!--" />-->
<!--    --><?php //endif; ?>
<?php //endif; ?>

<!--    --><?php //echo $_dataHelper->renderConfigCss(); ?>
<!--    --><?php //echo $_dataHelper->renderConfigJs(); ?>
<!---->
<!--    <script type="text/javascript" src="--><?php //echo $block->getViewFileUrl('MW_Onestepcheckout::js/view.js') ?><!--"></script>-->
<!--    <script type="text/javascript" src="--><?php //echo $block->getViewFileUrl('MW_Onestepcheckout::js/plugins/prototype.authorizenet_directpost.js') ?><!--"></script>-->
<!--    <!-- TODO: Check SagePay -->
<!--    <!-- <script type="text/javascript" src="--><?php //echo $block->getViewFileUrl('MW_Onestepcheckout::js/plugins/prototype.sagePaySuite_Checkout.js') ?><!--"></script> -->

<?php //endif; ?>
<script type="text/javascript">
    //    var isLogged = <?php //echo ($block->getCustomerSession()->isLoggedIn() ? 1 : 0) ?>//;

    var mw_baseUrl = '<?php echo $block->_getBaseUrl() ?>';
    var mw_post_baseUrl = 'http://localhost/projects/magento2/default/';
    var mw_ctrl = 'index';
    var mw_mdn = 'cms';
    var mw_act = 'index';
    var version_num = '1.9';
    var package_name = 'rwd';
    var theme_name   = 'default';
    var mw_session_id = "nqbh6rcdnu5phqbvmv6bo70gc1";
    var isLogged = '';
    var version = 'mc';

</script>



