<div id="mw-fg-slider-cart">
    <script type="text/javascript">
        hasGiftProduct = true;
    </script>
    <div class="mw-fg-cart-title">
        <strong>Select your free gift (s)</strong>
    </div>
    <div class="bCarousel-wrapper"><a href="#back" class="back show_arrow">&lt;</a><a href="#forward" class="forward show_arrow">&gt;</a><div id="the-carousel" class="bcarousel carousel-target" style="width: 225.5px; margin-left: 0px;">
            <ul id="freegift" class="jcarousel-skin-tango mw-fg-slide">
                <li class="mw-fg-items">
                    <a id="stay-target-3971524190057" href="http://demo.mage-world.com/190s5/madison-earbuds.html" title="" class="product-image">
                        <img src="http://demo.mage-world.com/190s5/media/catalog/product/cache/1/small_image/140x135/9df78eab33525d08d6e5fb8d27136e95/h/d/hde010_1.jpg" width="140" height="135" alt="">
                    </a>
                    <span style="display: none" class="product-name"><a href="javascript:;">Madison Earbuds</a></span>
                    <div id="stay-content-3971524190057" class="mw-fg-item" style="display: none;">
                        <div class="mw-fg-item-options">
                            <div class="mw-fg-item-option-title">
                                Buy A get a free                            </div>
                            <div class="mw-fg-item-option-ct">
                                <p class="mw-fg-item-name">
                                    <a href="http://demo.mage-world.com/190s5/madison-earbuds.html?mw_freegift=1" title="Madison Earbuds">Madison Earbuds</a>
                                </p>

                            </div>
                        </div>
                    </div>
                    <div class="product-shop">
                        <div class="f-fix">
                            <div class="old-price">
                                <span class="price">$35.00</span>                            </div>
                            <p>
                            </p><div class="mw-hidden-product" data-product-id="397"></div>
                            <div class="mw-hidden-product-image" data-product-image="http://demo.mage-world.com/190s5/media/catalog/product/cache/1/small_image/265x265/9df78eab33525d08d6e5fb8d27136e95/h/d/hde010_1.jpg"></div>
                            <div class="mw-hidden-product-has-options" data-has-options="0"></div>
                            <div class="mw-hidden-product-type" data-product-type-id="simple"></div>
                            <button id="btn" type="button" title="Add to Cart" data-has-options="0" data-type-id="simple" data-url-cart="http://demo.mage-world.com/190s5/checkout/cart/add/uenc/aHR0cDovL2RlbW8ubWFnZS13b3JsZC5jb20vMTkwczUvZnJlZWdpZnQvY2FydC91cGRhdGVQb3N0Lw,,/product/397/form_key/lKXpFNHnJw1qycKH/free_catalog_gift/2491/ajax_gift/1/applied_catalog_rule/1/" data-ffg-type="catalog" data-applied-catalog-rule="1" data-catalog-gift="2491" data-id="397" class="button btn-cart mw_rule" data-url="http://demo.mage-world.com/190s5/checkout/cart/add/uenc/aHR0cDovL2RlbW8ubWFnZS13b3JsZC5jb20vMTkwczUvZnJlZWdpZnQvY2FydC91cGRhdGVQb3N0Lw,,/product/397/form_key/lKXpFNHnJw1qycKH/free_catalog_gift/2491/ajax_gift/1/applied_catalog_rule/1/">
                                <span><span>Add to Cart</span></span>
                            </button>
                            <p></p>

                        </div>
                    </div>
                </li>
            </ul>
        </div></div>
</div>