<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="1500">
    <!-- Indicators -->
    <ol class="carousel-indicators" >
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" style="height: 300px">

        <div class="item active" >
                            <img src="<?php echo $this->getViewFileUrl('MW_FreeGift::images/tree.jpg')?>" alt="Message" style="width:100%;">
            <div class="carousel-caption" style="padding-bottom:50%">
            </div>
        </div>

        <div class="item" >
                            <img src="<?php echo $this->getViewFileUrl('MW_FreeGift::images/tree.jpg')?>" alt="Message" style="width:100%;">
            <div class="carousel-caption" style="padding-bottom:50%">
            </div>
        </div>
        <div class="item" >
                            <img src="<?php echo $this->getViewFileUrl('MW_FreeGift::images/tree.jpg')?>" alt="Message" style="width:100%;">
            <div class="carousel-caption" style="padding-bottom:50%">
            </div>
        </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon">Previous</span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon">Next</span>
        <span class="sr-only">Next</span>
    </a>
</div>
