    <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="1500">
        <!-- Indicators -->
        <ol class="carousel-indicators" >
<!--            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>-->
<!--            <li data-target="#myCarousel" data-slide-to="1"></li>-->
<!--            <li data-target="#myCarousel" data-slide-to="2"></li>-->
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" style="height: 100px; background-color: #eff5ea;">

            <div class="item active" >
<!--                <img src="--><?php //echo $this->getViewFileUrl('MW_FreeGift::images/tree.jpg')?><!--" alt="Message" style="width:100%;">-->
                <div class="carousel-caption" style="color: #3D6611; position: initial;">
                    <h3>Spend more $300 to get 3 free gift</h3>
                </div>
            </div>

            <div class="item" >
<!--                <img src="--><?php //echo $this->getViewFileUrl('MW_FreeGift::images/tree.jpg')?><!--" alt="Message" style="width:100%;">-->
                <div class="carousel-caption" style="color: #3D6611; position: initial;">
                    <h3>Spend more $400 to get 4 free gift</h3>
                </div>
            </div>
            <div class="item" >
<!--                <img src="--><?php //echo $this->getViewFileUrl('MW_FreeGift::images/tree.jpg')?><!--" alt="Message" style="width:100%;">-->
                <div class="carousel-caption" style="color: #3D6611; position: initial;">
                    <h3>Spend more $600 to get 6 free gift</h3>

                </div>
            </div>

        </div>
    </div>
